// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import KeywordsForTriggerController from "./keywords_for_trigger_controller"
application.register("keywords-for-trigger", KeywordsForTriggerController)
