meta_product_name: "QuickReach"
meta_title: "QuickReach - Sales Outreach automation for relevant breaking news"
meta_description: "Sales Outreach automation for relevant breaking news"
meta_image: "cover.png" # should exist in `app/assets/images/`
